### ISSUE TITLE
Document library addition

### ISSUE THREAD

**Issue by maxwildersmith** [Bronco-Space/simulation#40]
Just leave a comment on here documenting how to add 3rd-party libraries to the simulation.

**Comment by notBajaBlast** [comment]
Steps to add libraries to Python in blender (Windows).
1.	In the blender command prompt, enter “import sys” followed by “sys.exec_prefix”
2.	Enter “cd” followed by the address given and open Microsoft PowerShell.
3.	Type “.\bin\python.exe -m ensurepip” to make sure you have pip installed.
4.	Type “.\scripts\pip3.exe install *insert package(s) name(s) here without asterisks* to download the packages for use in blender.

**Comment by notBajaBlast** [comment]
Modules needed:
https://github.com/KieranWynn/pyquaternion
