### ISSUE TITLE
List of useful mechanical/physical values

### ISSUE THREAD

**Issue by maxwildersmith** [Bronco-Space/simulation#5]
Come up with a preliminary list of data/values that would be useful for mechanical/hardware analysis. Things like center of mass, drag, velocity, etc.

**Comment by notBajaBlast** [comment]
-Central force motion of satellite [orbital movement]
-Orbital Velocity
-Angular Velocity of Satellite's Rotation
-Angular momentum
- Weight of object at altitude 
-Gravitational acceleration at altitude
-Drag
-Center of  Mass
-Orbital Period
