### ISSUE TITLE
Research Reaction Wheel

### ISSUE THREAD

**Issue by maxwildersmith** [Bronco-Space/simulation#62]
Document on this issue the inputs/outputs for each reaction wheel, as well as what sorta physics system we would need to add for the interactions.

**Comment by notBajaBlast** [comment]
1) https://digitalcommons.usu.edu/cgi/viewcontent.cgi?article=1456&context=gradreports
2) https://ocw.mit.edu/courses/aeronautics-and-astronautics/16-83x-space-systems-engineering-spring-2002-spring-2003/projects/design_final_e.pdf
3) https://ntrs.nasa.gov/api/citations/20110015369/downloads/20110015369.pdf
4) https://eng.libretexts.org/Bookshelves/Electrical_Engineering/Signal_Processing_and_Modeling/Book%3A_Introduction_to_Linear_Time-Invariant_Dynamic_Systems_for_Students_of_Engineering_(Hallauer)/03%3A_Mechanical_Units_Low-Order_Mechanical_Systems_and_Simple_Transient_Responses_of_First_Order_Systems/3.03%3A_Reaction_Wheel
